apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: webserver
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 22
        volumeMounts:
        - name: laravel-code
          mountPath: /var/www
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: php-config
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        envFrom:
        - configMapRef:
            name: laravel-config
      - name: app
        image: php:8.2-fpm
        volumeMounts:
        - name: laravel-code
          mountPath: /var/www
        workingDir: /var/www
        envFrom:
        - configMapRef:
            name: laravel-config
      - name: db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "terrain_booking"
        - name: MYSQL_USER
          value: "laravel"
        - name: MYSQL_PASSWORD
          value: "laravel"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: laravel-code
        hostPath:
          path: /d/Year4(ITC)/SEMESTER2/Devops/finalexam/laravel
          type: Directory
      - name: nginx-config
        hostPath:
          path: /d/Year4(ITC)/SEMESTER2/Devops/finalexam/nginx.conf
          type: File
      - name: php-config
        hostPath:
          path: /d/Year4(ITC)/SEMESTER2/Devops/finalexam/php.ini
          type: File
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
  - name: http
    port: 8100
    targetPort: 80
    nodePort: 31000 # Minikube NodePort range: 30000-32767
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 31001
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_NAME: "Terrain Booking"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "http://localhost:8100"
  DB_HOST: "db"
  DB_PORT: "3306"
  DB_DATABASE: "terrain_booking"
  DB_USERNAME: "laravel"
  DB_PASSWORD: "laravel"
  SESSION_DRIVER: "database"
  QUEUE_CONNECTION: "database"
  CACHE_STORE: "database"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi